### PR TITLE
Assorted bug fixes

### PR DESCRIPTION
**Pull request by gcampax**
See individual commits

### CODE REVIEW

**Review by rayslxu — APPROVED** [review]
Looks good. 
I'm not sure about #483 though - pretty much all the news apis return RDL with title and we probably want to read that. the fix is fine for the skills we have right now, but in the future, we need something smarter.

**Comment by rayslxu** [comment]
For #483

> Looks good.
> I'm not sure about #483 though - pretty much all the news apis return RDL with title and we probably want to read that. the fix is fine for the skills we have right now, but in the future, we need something smarter.

**Comment by gcampax** [comment]
You don't want to read the news title straight up, you want to construct a sentence that contains the news title, using the `#[result]` phrase, and read that. So the RDL is always redundant. At least, that's what the SmartNews skill does.

**Comment by rayslxu** [comment]
> You don't want to read the news title straight up, you want to construct a sentence that contains the news title, using the `#[result]` phrase, and read that. So the RDL is always redundant. At least, that's what the SmartNews skill does.

So in text mode, there will be a phrase as well as the RDL link with redundant information?

**Comment by gcampax** [comment]
Yes. I believe that's the design on Google Assistant as well, judging from their documentation around card outputs.

**Pull request merged**
