### PR TITLE
Clean up the template build system

### PR DESCRIPTION
**Pull request by gcampax**
This RFC PR comes from the observation that people won't be writing Genie templates and distribute them as separate packages. 

Core features that require new ThingTalk will be developed inside Genie itself (or maybe as a fork of Genie), while custom dialogues will be represented in some higher level way that doesn't involve writing templates directly.

Once we accept that, we can clean up how templates and the rest of the sentence generator runtime are linked together. This is a cleanup in preparation for changing how agent policies are expressed, which will change all the business around context tags and "context"/"answer" functions in the dialogue templates, and couple dialogue templates even tighter to the rest of the dialogue agent.

Side effects of this PR:
- custom template files are gone, and the --template option to `genie generate` is no longer useful: it is still there to select betwene "basic" (exact match) and "single-sentence" templates (full thingtalk)
- #590 is fixed because we don't call typescript twice

### CODE REVIEW

**Review by rayslxu — APPROVED** [review]
on one hand, I like the changes with a much cleaner structure, but on the other hand, I feel I will have a painful time when rebasing my ongoing branches...

**Comment by gcampax** [comment]
Do you have a lot of outstanding branches? I'm hoping that git recognizes these are just renames and will do the right thing, but you might have to cherry-pick changes by hand...

**Comment by gcampax** [comment]
It actually looks like git can pick up the rename just fine, I am seeing basically no merge conflicts when I merged with the other PR on the command-line.

**Comment by rayslxu** [comment]
> It actually looks like git can pick up the rename just fine, I am seeing basically no merge conflicts when I merged with the other PR on the command-line.

oh, cool. i have just one branch for wikidata now actually and it's not touching the templates so far. so it should be fine anyway

**Pull request merged**
