### PR TITLE
Fix circular dependency in genie tokenizer

### PR DESCRIPTION
**Pull request by rayslxu**
`./lib/i18n` -> `./lib/i18n/default.ts` -> `./lib/utils/template-strings` -> `./lib/i18n/`

### CODE REVIEW

**Review by gcampax — COMMENTED** [review]
This commit causes us to create new Tokenizer instances repeatedly. This is not very efficient because we end up initializing a whole bunch of regular expressions every time.
It's also a potential source of bugs in the future because now there are two sources of truth wrt which languages are supported, one here and one in i18n/index

Is there no other way to resolve the circular import?

**Comment by gcampax** [comment]
E.g. what if we import template-strings from i18n/index before we import default.ts ?

**Comment by rayslxu** [comment]
> E.g. what if we import template-strings from i18n/index before we import default.ts ?

I don't follow. Isn't that still circular? as `./lib/i18n` and './lib/utils/template-strings/` gonna import from each other?

**Comment by gcampax** [comment]
Yes but template-strings doesn't need anything from I18n during the initial module evaluation. So it will receive an empty object (while I18n continues initializing), declare a bunch of classes, and move on happily.

**Review by gcampax — APPROVED** [review]
Nice yeah

**Pull request merged**
