### PR TITLE
Disable support for multidomain contexts

### PR DESCRIPTION
**Pull request by gcampax**
This is a large hammer to solve some of the batch size issues we're
seeing in the Thingpedia model, as we generate contexts that are
too long. With this change, the context will contain at most
one statement, and therefore will be quite short, at the expense
of not supporting any multi-domain parameter passing.

This commit is incompatible with MultiWOZ and will need to be
reverted or made into an option.

@s-jse comments? I can't see any other way to avoid continuous batch size problems.

### CODE REVIEW

**Comment by s-jse** [comment]
Batch size problems? What batch size problems?

**Comment by gcampax** [comment]
We keep hitting CUDA OOM errors, and we keep lowering the batch size. But the batch size is ~11 now, which is too low and unsustainable because we don't even see the whole dataset in one training.

**Comment by s-jse** [comment]
> 
> 
> We keep hitting CUDA OOM errors, and we keep lowering the batch size. But the batch size is ~11 now, which is too low and unsustainable because we don't even see the whole dataset in one training.

And what would be the batch size after this change?

**Comment by gcampax** [comment]
Batch size should be the same I think, but the number of examples in each batch should be larger because each example will have a shorter context on average. Although tbqh I am not sure why we hit CUDA OOM given that we specify the batch size in tokens and not in examples.

**Comment by s-jse** [comment]
Batch size is specified by the number of tokens **in the input**, but the memory consumption on GPU is roughly a function of maximum of input and output lengths. The reason we use input length alone for specifying the batch size is that 1) In `TransformerLSTM` models, memory is dominated by the encoder, so input length is the only thing that matters, and 2) length of the output is not known in some cases since we don't have access to the gold output (or even if we did, generated output can have a different length than the gold output).
So two batches that both fit into the specified size limit can have different output lengths, and therefore one of them may result in OOM.

**Comment by gcampax** [comment]
This is not very efficient. Can we change the specification to account for input and output length? The only case where we don't know the output length is when running in the server, but batching for the server is done client side so it doesn't matter.

**Comment by s-jse** [comment]
> 
> 
> This is not very efficient. Can we change the specification to account for input and output length? The only case where we don't know the output length is when running in the server, but batching for the server is done client side so it doesn't matter.

I opened an issue for this in genienlp: https://github.com/stanford-oval/genienlp/issues/91.
Anyways, for this PR I would say let's measure the difference in the maximum number of examples we can fit into a batch after this change to see if it is significant. You can merge this, I just want to know the number.

**Review by s-jse — APPROVED** [review]

**Comment by gcampax** [comment]
I started job 95, I will let you know.

**Comment by gcampax** [comment]
It's a bit difficult to notice the number, but I think it oscillates between 10 and 13, with the occasional 14.

**Comment by gcampax** [comment]
It doesn't seem to affect accuracy, or affect batch sizes too much, so I'm not sure I'll merge this after all.

**Comment by gcampax** [comment]
We're not going to merge this after all.

**Pull request closed without merging**
