### PR TITLE
Remove remaining traces of decanlp

### PR DESCRIPTION
**Pull request by Mehrad0711**
A truly small PR

### CODE REVIEW

**Comment by Mehrad0711** [comment]
Tests are failing on master too...

**Comment by gcampax** [comment]
Yes you're not supposed to merge to master, merge to next.

**Comment by gcampax** [comment]
You'll need a rebase to remove extraneous stuff

**Comment by Mehrad0711** [comment]
Wait this change is meant to be for master. I already included it in the PR for next.
Is master not maintained anymore?

**Comment by gcampax** [comment]
I'll be merging next into master as soon as Silei finishes the schema2qa port (he told me hopefully today, by monday at the latest) and then we'll close next.

**Comment by Mehrad0711** [comment]
Sounds good.

**Pull request closed without merging**
